### ISSUE TITLE
2022.24200

### ISSUE THREAD

**Issue by minusninebelow** [kamindustries/td-scope#2]
this is a fantastic network.  I recently upgraded to the most recent TD - 2022.24200 and seems there were some breaking changes.  Looking at the network when it runs it may be in the GL code; but I know very little GL code to troubleshoot beyond.  Any chance of taking a look?

Thanks!

**Comment by kamindustries** [comment]
Hey, thanks for checking it out! Can you try this branch and see if it fixes the issue for you?

https://github.com/kamindustries/td-scope/tree/texelfetch-fix

**Comment by minusninebelow** [comment]
yessir looks good.  thank you for the super quick response.  I plan on integrating this patch to display raw synthesized waveforms via laser.   will send some vids or feedback once i get it working!

**Comment by kamindustries** [comment]
I've been asked this question before about getting it to work on a laser projector. I think in its current form it might be challenging since the waveform you're seeing is being drawn in a vertex shader on the gpu. AFAIK a laser projector needs information from CHOPs on the cpu. The shader isn't that heavy, so I think the best bet is to start by transcribing the algorithm to python to create an array in chops that will be your path for the laser to scan. You'll also need to add logic for blanking as well. 

If I'm misunderstanding please let me know, or you get it working at all I'd love to see it. I don't have a laser projector on hand to test with otherwise I'd work on it myself.
